### ISSUE TITLE
Deploy an NFT collection contract - FetchError: Internal Server Error

### ISSUE THREAD

**Issue by Hye1Kim** [Worldsz/NFT-Unity3D-Metaverse-Template#6]
Although local sent a request to distribute the NFT collection contract this time, the following error message was displayed.
```

FetchError: Internal Server Error
    at new FetchError (/home/pslab2/node_modules/api/dist/core/errors/fetchError.js:21:28)
    at APICore.<anonymous> (/home/pslab2/node_modules/api/dist/core/index.js:152:51)
    at step (/home/pslab2/node_modules/api/dist/core/index.js:44:23)
    at Object.next (/home/pslab2/node_modules/api/dist/core/index.js:25:53)
    at fulfilled (/home/pslab2/node_modules/api/dist/core/index.js:16:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  status: 500,
  data: {
    response: 'NOK',
    error: {
      status_code: 500,
      code: 'internal_server_error',
      message: 'The request could not be completed due to an internal server error.'
    }
  },
  headers: Headers {
    [Symbol(map)]: [Object: null prototype] {
      server: [Array],
      date: [Array],
      'content-type': [Array],
      'content-length': [Array],
      'access-control-allow-origin': [Array],
      'access-control-allow-headers': [Array],
      'access-control-allow-methods': [Array],
      via: [Array],
      'alt-svc': [Array],
      connection: [Array]
    }
  },
  res: Response {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: { body: [PassThrough], disturbed: true, error: null },
    [Symbol(Response internals)]: {
      url: 'https://api.nftport.xyz/v0/contracts/collections',
      status: 500,
      statusText: 'Internal Server Error',
      headers: [Headers],
      counter: 0
    }
  }
}
```

**Comment by saszer** [comment]
Please try again or provide more info.
Also ,This is unrelated to this Sample or unity SDK - please divert via https://discord.gg/7SZrVZRs32.
